<?php
$images = $this->getAllImages();
$effectsConfig = Mage::helper('slider')->getEffectsConfig();
?>

<div class="slider-container">
    <div class="swiper-wrapper">
        <?php foreach($images as $value) : ?>
            <div class="swiper-slide">
                <?php if($value['title']): ?>
                    <h3 class="title">
                        <?php echo $value['title'] ?>
                    </h3>
                <?php endif; ?>
                <img src="<?php echo $value['image_path'] ?>">
            </div>
        <?php endforeach; ?>
    </div>
    <div class="slider-pagination"></div>
</div>

<script>
    var mySwiper = new Swiper('.slider-container',{
        <?php echo $effectsConfig['pagination']? "pagination : '.slider-pagination'," : '' ?>
        paginationClickable: true,
        moveStartThreshold: 100,
        <?php echo $effectsConfig['autoplay'] ? "autoplay : 10000," : '' ?>
        <?php echo $effectsConfig['loop'] ? "loop : true," : 'loop : false,' ?>
        mode: '<?php echo $effectsConfig['mode' ]==2 ? 'vertical' : 'horizontal' ?>'

    })
</script>